version: "3"
services:
  haproxy:
    restart: "no"
    build:
      context: ./haproxy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./haproxy/:/usr/local/etc/haproxy/
      - ./key/:/key/
    ports:
      - 8001:80
    links:
      - redis
      - app
    depends_on:
      - redis
      - app
  app:
    restart: "no"
    build:
      context: ./nodejs
    ports:
      - 8002:3000
    volumes:
      - ./key/:/key/
  redis:
    restart: "no"
    image: redis:5.0.3
